security:
    role_hierarchy:
        ROLE_USER: [] # rôle de base
        ROLE_CANDIDAT: [ROLE_USER]
        ROLE_ETABLISSEMENT: [ROLE_CANDIDAT, ROLE_USER]
        ROLE_COMMISSION: [ROLE_AGENT, ROLE_CANDIDAT, ROLE_USER]
        ROLE_AGENT: [ROLE_CANDIDAT, ROLE_USER]
        ROLE_ADMIN:
            [
                ROLE_AGENT,
                ROLE_COMMISSION,
                ROLE_ETABLISSEMENT,
                ROLE_CANDIDAT,
                ROLE_USER,
            ]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
                csrf_token_id: authenticate
                default_target_path: after_login
                always_use_default_target_path: true
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/commission, roles: ROLE_COMMISSION }
        - { path: ^/etablissement, roles: ROLE_ETABLISSEMENT }
        - { path: ^/equivalence, roles: IS_AUTHENTICATED_FULLY } # ou ROLE_USER
